name: Regression Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.html'
      - '*.md'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Let's try opting into use of Nodejs v24; see:
      #  https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
      # GitHub runners still causing problems with NodeJS v20; see:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      DEBIAN_FRONTEND: noninteractive
      LDAP_HOST: ldap
      TZ: America/Los_Angeles

    services:
      ldap:
        # Docker Hub image
        image: osixia/openldap:1.5.0
        env:
          LDAP_ADMIN_PASSWORD: castaglia
          LDAP_BASE_DN: DC=castaglia,DC=org
          # Used for TLS certs
          LDAP_DOMAIN: castaglia.org
          LDAP_READONLY_USER: 'true'
          LDAP_READONLY_USER_USERNAME: readonly
          LDAP_READONLY_USER_PASSWORD: readonly
          # Needed for posixAccount support
          LDAP_RFC2307BIS_SCHEMA: 'true'
          LDAP_TLS_VERIFY_CLIENT: never
        # Set health checks to wait until OpenLDAP has started
        options: >-
          --health-cmd "cat /run/slapd/slapd.pid"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        compiler:
          - gcc
        container:
          - ubuntu:22.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v6
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout module source code
        uses: actions/checkout@v6
        with:
          path: proftpd/contrib/mod_sftp_ldap

      - name: Install Ubuntu packages
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y gcc git make tzdata

          # for LDAP support 
          apt-get install -y libldap2-dev libsasl2-dev ldap-utils
          # for OpenSSL support
          apt-get install -y libssl-dev

          # for integration/regression tests
          apt-get install -y \
            libauthen-oath-perl \
            libcompress-raw-zlib-perl \
            libdata-dumper-simple-perl \
            libdatetime-perl \
            libfile-copy-recursive-perl \
            libfile-path-tiny-perl \
            libfile-spec-native-perl \
            libmime-base32-perl \
            libnet-address-ip-local-perl \
            libnet-inet6glue-perl \
            libnet-ssh2-perl \
            libnet-ssleay-perl \
            libnet-telnet-perl \
            libposix-2008-perl \
            libtest-unit-perl \
            libtime-hr-perl \
            libwww-perl
          PERL_MM_USE_DEFAULT=1 perl -MCPAN -e 'install Net::FTPSSL'

          # for debugging
          gcc --version
          openssl version -a

      - name: Install with static modules
        # NOTE: Docker does not have good IPv6 support, hence we disable it.
        run: |
          cd proftpd
          ./configure --disable-ipv6 --with-modules=mod_ldap:mod_sftp:mod_sftp_ldap
          make
          ./proftpd -V
          make install

      - name: Run integration tests
        env:
          PROFTPD_TEST_BIN: /usr/local/sbin/proftpd
          PROFTPD_TEST_CI: github
          PROFTPD_TEST_DIR: ${{ github.workspace }}/proftpd/tests
        run: |
          cd proftpd/contrib/mod_sftp_ldap
          ldapadd -x -D "cn=admin,dc=castaglia,dc=org" -w castaglia -H ldap://ldap -f t/etc/ldap/castaglia.ldif
          perl tests.pl
